import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cx } from "class-variance-authority";
import { NextAuthProvider } from "@/providers/next-auth";
import { getServerSession } from "next-auth";
import { NextAuthConfig } from "@/lib/next-auth/auth-options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(NextAuthConfig);
  return (
    <html lang="en">
      <body className={cx("min-h-screen flex flex-col", inter.className)}>
        <NextAuthProvider session={session}>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
